### ISSUE TITLE
Support Unsetting Variables

### ISSUE THREAD

**Issue by bbatsche** [jakzal/phpunit-globals#26]
It is not currently possible to ensure an environment variable is unset completely for a test, ~~or that variables that were not previously set before a test started are unset at the end.~~ (Update: I missed the call to `putenv($name)` to unset modified variables, my mistake) For example:

```php
getenv('FOO');
// returns false

setenv('FOO=bar');
getenv('FOO');
// returns 'bar'

setenv('FOO=');
getenv('FOO')
// returns '' (empty string); this is what PHPUnit Globals currently supports

setenv('FOO');
getenv('FOO');
// returns false; this is not currently supported
```

I'd be happy to put together a PR for this if you're interested in adding it, and maybe take a crack at #25 while I'm at it.

**Comment by jakzal** [comment]
Sure, if you need to unset variables I'll be happy to merge a PR.

Also, #25 is something that many people are looking forward to! I haven't looked at the new event system in the upcoming major PHPUnit release. Perhaps that could help.

**Comment by bbatsche** [comment]
I've dug into PHPUnit's new events for the last few weeks, so yeah I had the same thought! I'll see what I can whip up.

**Comment by jakzal** [comment]
Fixed by #27

**Comment by jakzal** [comment]
Here's an extension that was migrated to the new event system for PHPUnit 10: https://github.com/johnkary/phpunit-speedtrap/pull/98/files

**Comment by jakzal** [comment]
See https://github.com/jakzal/phpunit-globals/pull/31 for PHPUnit 10 support.
