### ISSUE TITLE
PHPUnit 10 support

### ISSUE THREAD

**Issue by jdecool** [jakzal/phpunit-globals#33]
PHPUnit 10 was released a few days ago.

It would be great to update this library to be compatible with it.

 * [Changelog](https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md)

**Comment by jakzal** [comment]
fixed by #31

**Comment by jshah4517** [comment]
@jakzal would you be willing to tag a stable release?

**Comment by jakzal** [comment]
Done https://github.com/jakzal/phpunit-globals/releases/tag/v3.0.0.
