### ISSUE TITLE
Backport attribute management to 2.5

### ISSUE THREAD

**Issue by jdecool** [jakzal/phpunit-globals#38]
Since it could be not trivial to migrate from PHPUnit 9 to 10, it could be very interesting to use attributes.

But it's only available in 3.0 which is compatible with PHPUnit, are you open to a PR to back port attribute mechanism to the 2.5 branch ?

**Comment by jakzal** [comment]
We would need to release 2.6 I guess. 

Is it really not trivial to migrate PHPUnit? What are the main blockers? Is it the new event system?

If this is really what people want/need and you're happy to do the work (which we will release as 2.6), then I have nothing against it. As on 3.x we'd need to deprecate annotations on 2.6 though.

Sorry, I thought I'd just be doing bug fixes on 2.5 at this point, so I'd like to make sure I'm not going to bring whole lot of maintenance burden first 😂

**Comment by jdecool** [comment]
> Is it really not trivial to migrate PHPUnit?

Big code base can be hard to migrate.

The main pain point I've encountered is about `data providers` that are becoming `static`.
But some code contains a lot of reference to `$this`

**Comment by jakzal** [comment]
Released as [v2.6.0](https://github.com/jakzal/phpunit-globals/releases/tag/v2.6.0).

**Comment by jdecool** [comment]
Thanks
