### ISSUE TITLE
Support for PHP 8.4

### ISSUE THREAD

**Issue by j-schumann** [jakzal/phpunit-globals#49]
Hello,

since 8.4 is out, could we get support for it in the composer.json?

And may I ask, what is the reason not to support all upcoming 8.x versions with "^8.1"? Do you fear there might be incompatible changes?
Because it would be good, to be able to test projects against upcoming PHP versions, like many projects to, e.g. Symfony: https://github.com/symfony/symfony/commit/5f8fc3a9f6ca3444b1723a34b7f641ae4818bdaf

Thanks in advance,
JS

**Comment by jakzal** [comment]
> Do you fear there might be incompatible changes?

Yes. Until I have a passing build, I won't know if it works. 

PHP doesn't follow semantic versioning.

**Comment by j-schumann** [comment]
> Yes. Until I have a passing build, I won't know if it works.

@jakzal, exactly, that is why I think it is important to test early against upcoming (PHP) versions. To detect incompatiblities before release and ideally have a compatible version of the own product ready when the new version of the dependency releases.
This is especially important for tools that themselves are used for testing other libraries: Without them being compatible with the upcoming version, the other libs cannot be tested in advance.

phpunit-globals seems to work with the current state of 8.5: https://github.com/j-schumann/phpunit-globals/actions/runs/12082543741

**Comment by jakzal** [comment]
@j-schumann that build has failed due to a PHPUnit warning:

```
PHPUnit 11.4.4 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.5.0-dev
Configuration: /home/runner/work/phpunit-globals/phpunit-globals/tests/phar/phpunit.xml

..                                                                  2 / 2 (100%)

Time: 00:00.005, Memory: 8.00 MB

There was 1 PHPUnit test runner warning:

1) Cannot load extension from /home/runner/work/phpunit-globals/phpunit-globals/tests/phar/tools/phpunit.d/zalas-phpunit-globals-extension.phar: Loading phar:///home/runner/work/phpunit-globals/phpunit-globals/tests/phar/tools/phpunit.d/zalas-phpunit-globals-extension.phar/manifest.xml failed.

WARNINGS!
Tests: 2, Assertions: 4, Warnings: 1, PHPUnit Deprecations: 1.
```

**Comment by j-schumann** [comment]
Yes, this is what I said in https://github.com/jakzal/phpunit-globals/pull/52#issue-2698910789, in my fork the integration tests fail, but they work in your repository, I guess that has something to do with repository settings/variables or the repository name itself. 

I will create a PR for main, we can than see if the build runs through.

**Comment by j-schumann** [comment]
@jakzal, the build in #53 passed, what do you think? 
By testing on future PHP versions in the GH pipeline it should be possible to detect errors early, thus changing the composer.json to `"php": "^8.1.0"` seems safe. Except maybe on the 2.x branch when you don't want to support new PHP versions there and get people to switch to 3.x / main.
